@startuml

skinparam dpi 300

actor email_alert_service as "email-alert-service"
participant controller as "ContentChangeController"
database content_change as "ContentChange"
participant subscription_content_worker as "SubscriptionContentWorker"
participant subscription_matcher as "SubscriptionMatcher"
database subscription_content as "SubscriptionContent"
participant email_generation_worker as "EmailGenerationWorker"
control digest_timer as "DigestTimer"
database email as "Email"
participant email_renderer as "EmailRenderer"
participant delivery_request_worker as "DeliveryRequestWorker"
database delivery_attempt as "DeliveryAttempt"
control delivery_monitor as "DeliveryMonitor"
participant govuk_notify as "GOV.UK Notify" #orange

email_alert_service -> controller : POST /create
controller -> content_change : create
content_change -> controller : id
controller -> subscription_content_worker : enqueue with id
controller -> email_alert_service : acknowledge

group sidekiq
  subscription_content_worker -> content_change : find by id
  content_change -> subscription_content_worker : instance
  subscription_content_worker -> subscription_matcher : content_change
  subscription_matcher -> subscription_matcher : ... existing logic
  subscription_matcher -> subscription_content_worker : subscriptions
  subscription_content_worker -> subscription_content : create with subscription, content_change
  subscription_content_worker -> email_generation_worker : enqueue with 'immediate'
  subscription_content_worker -> content_change : set processed_at and save
end group

group daily timer
  digest_timer -> email_generation_worker : enqueue with 'daily'
end

group weekly timer
  digest_timer -> email_generation_worker : enqueue with 'weekly'
end

group sidekiq
  email_generation_worker -> subscription_content : find all by frequency, email_id=nil
  subscription_content -> email_generation_worker : instances
  email_generation_worker -> email_generation_worker : group by subscription
  email_generation_worker -> email : build with subscription_content
  email -> email_generation_worker : instance
  email_generation_worker -> email_renderer : email
  email_renderer -> email_generation_worker : subject, body
  email_generation_worker -> email : set subject, body
  email_generation_worker -> email : set recipient and save
  email -> subscription_content : (active record automatically sets email_id)
  email -> email_generation_worker : id
  email_generation_worker -> delivery_request_worker : enqueue with id
  email_generation_worker -> subscription_content : set processed_at and save
end

group sidekiq
  delivery_request_worker -> email : find by id
  email -> delivery_request_worker : instance
  delivery_request_worker -> delivery_attempt : create with email, state=ready_to_send
  delivery_attempt -> delivery_request_worker : instance
  delivery_request_worker -> govuk_notify : request to deliver email
  delivery_request_worker -> delivery_attempt : set state=sent_to_notify and save
  delivery_request_worker -> email : set processed_at and save
end group

group run continuously
  delivery_monitor -> delivery_attempt : find by state=sent_to_notify
  delivery_attempt -> delivery_monitor : instance
  delivery_monitor -> govuk_notify : get status
  govuk_notify -> delivery_monitor : status

  group if success
    delivery_monitor -> delivery_attempt : set success
    delivery_monitor -> delivery_attempt : save
  end group

  group if failed
    delivery_monitor -> delivery_attempt : set failed, error message
    delivery_monitor -> delivery_attempt : save
    delivery_monitor -> delivery_attempt : find others for email
    delivery_attempt -> delivery_monitor : instances
    delivery_monitor -> delivery_monitor : ... decide what to do\ne.g. retry in an hour\ne.g. blacklist subscriber
  end group

  delivery_monitor -> delivery_monitor : sleep 1
end group

@enduml
