module AllTaxonomyTopics
  def taxonomy_topic_urls
    %w[/coronavirus-taxon/working-from-home
       /coronavirus-taxon/getting-financial-support-during-coronavirus
       /coronavirus-taxon/working-safely
       /coronavirus-taxon/help-with-redundancy-and-finding-work-during-coronavirus
       /coronavirus-taxon/entering-england
       /coronavirus-taxon/your-responsibilities-as-an-employer
       /coronavirus-taxon/self-employed-people-and-sole-traders
       /coronavirus-taxon/managing-your-business-during-coronavirus
       /coronavirus-taxon/funding-and-support
       /coronavirus-taxon/closures-exams-managing-school
       /coronavirus-taxon/further-higher-education-vocational
       /coronavirus-taxon/vaccinations
       /coronavirus-taxon/work-and-financial-support
       /coronavirus-taxon/education-and-childcare
       /coronavirus-taxon/rules-and-restrictions
       /coronavirus-taxon/driving-and-transport-in-the-uk
       /coronavirus-taxon/housing-and-accommodation
       /coronavirus-taxon/businesses-and-self-employed-people
       /coronavirus-taxon/international-travel-immigration-repatriation
       /coronavirus-taxon/healthcare-workers-carers-and-care-settings
       /coronavirus-taxon/health-and-wellbeing
       /coronavirus-taxon/volunteering-and-offering-help
       /coronavirus-taxon/testing
       /coronavirus-taxon
       /world/british-embassy-or-high-commission-french-polynesia
       /world/british-embassy-or-high-commission-new-caledonia
       /world/british-embassy-or-high-commission-central-african-republic
       /transport/self-driving-vehicles
       /education/t-levels
       /life-circumstances/lasting-power-attorney
       /life-circumstances/missing-persons
       /brexit
       /brexit/guidance-individuals
       /brexit/business-guidance
       /business-and-industry/artificial-intelligence
       /government/data
       /housing-local-and-community/traveller-communities
       /housing-local-and-community/housing-and-communities
       /government/digital-accessibility
       /government/digital-inclusion
       /education/set-up-independent-school
       /society-and-culture/digital-inclusion-and-accessibility-in-society
       /transport/hgv-bus-and-trailer-mot-tests
       /transport/road-haulage
       /transport/freight-haulage-and-cargo
       /health-and-social-care/sexual-and-reproductive-health
       /society-and-culture/city-of-culture
       /transport/lorry-bus-coach-and-specialist-vehicle-driving-tests
       /business-and-industry/space
       /world/all
       /world/british-embassy-or-high-commission-tonga
       /world/british-embassy-or-high-commission-niger
       /world/brexit-switzerland
       /world/brexit-norway
       /world/brexit-austria
       /world/brexit-belgium
       /world/brexit-bulgaria
       /world/brexit-croatia
       /world/brexit-cyprus
       /world/brexit-czech-republic
       /world/brexit-france
       /world/brexit-germany
       /world/brexit-denmark
       /world/brexit-estonia
       /world/brexit-finland
       /world/brexit-hungary
       /world/brexit-latvia
       /world/brexit-lithuania
       /world/brexit-malta
       /world/brexit-netherlands
       /world/brexit-portugal
       /world/brexit-slovakia
       /world/brexit-slovenia
       /world/brexit-spain
       /world/brexit-sweden
       /world/brexit-ireland
       /world/brexit-italy
       /world/brexit-luxembourg
       /world/brexit-romania
       /world/brexit-poland
       /world/brexit-greece
       /world/brexit-iceland
       /world/brexit-liechtenstein
       /world/british-embassy-or-high-commission-holy-see
       /world/british-embassy-or-high-commission-aruba
       /world/british-embassy-or-high-commission-st-maarten
       /world/british-embassy-or-high-commission-bonaire-st-eustatius-saba
       /world/british-embassy-or-high-commission-curacao
       /world/british-embassy-or-high-commission-cape-verde
       /society-and-culture/online-safety
       /coronavirus-taxon/holiday-and-sick-leave
       /coronavirus-taxon/childcare-for-workers
       /coronavirus-taxon/business-closures
       /coronavirus-taxon/how-you-can-help
       /coronavirus-taxon/pupil-wellbeing-safety
       /coronavirus-taxon/funding-support-education
       /coronavirus-taxon/student-accommodation-travel-finances
       /coronavirus-taxon/school-curriculum-and-teaching
       /world/living-in-iceland
       /world/living-in-norway
       /world/living-in-liechtenstein
       /world/living-in-switzerland
       /world/living-in-sweden
       /world/living-in-spain
       /world/living-in-slovenia
       /world/living-in-slovakia
       /world/living-in-romania
       /world/living-in-portugal
       /world/living-in-poland
       /world/living-in-netherlands
       /world/living-in-malta
       /world/living-in-luxembourg
       /world/living-in-lithuania
       /world/living-in-latvia
       /world/living-in-italy
       /world/living-in-ireland
       /world/living-in-hungary
       /world/living-in-greece
       /world/living-in-germany
       /world/living-in-france
       /world/living-in-finland
       /world/living-in-estonia
       /world/living-in-denmark
       /world/living-in-czech-republic
       /world/living-in-cyprus
       /world/living-in-croatia
       /world/living-in-bulgaria
       /world/living-in-belgium
       /world/living-in-austria
       /world/liechtenstein
       /world/norway
       /world/iceland
       /world/switzerland
       /world/sweden
       /world/spain
       /world/slovenia
       /world/slovakia
       /world/romania
       /world/portugal
       /world/poland
       /world/netherlands
       /world/malta
       /world/luxembourg
       /world/lithuania
       /world/latvia
       /world/italy
       /world/ireland
       /world/hungary
       /world/greece
       /world/germany
       /world/france
       /world/finland
       /world/estonia
       /world/denmark
       /world/czech-republic
       /world/cyprus
       /world/croatia
       /world/bulgaria
       /world/belgium
       /world/austria
       /world/transition
       /environment/low-carbon-technologies
       /environment/oil-gas-coal
       /environment/energy-infrastructure
       /business-and-industry/gambling-regulation
       /business-and-industry/alcohol-sales
       /world/british-embassy-or-high-commission-samoa
       /world/british-embassy-or-high-commission-maldives
       /world/british-embassy-or-high-commission-antigua-and-barbuda
       /world/british-embassy-or-high-commission-grenada
       /world/news-and-events-syria
       /world/british-embassy-or-high-commission-comoros
       /world/british-embassy-or-high-commission-st-vincent-and-the-grenadines
       /world/british-embassy-or-high-commission-bahamas
       /world/british-embassy-or-high-commission-vanuatu
       /world/living-in-australia
       /world/living-in-argentina
       /world/living-in-canada
       /world/living-in-india
       /world/living-in-saudi-arabia
       /world/living-in-south-africa
       /world/living-in-thailand
       /world/living-in-turkey
       /world/living-in-the-usa
       /world/living-in-myanmar
       /world/british-embassy-or-high-commission-eswatini
       /world/british-embassy-or-high-commission-american-samoa
       /world/news-and-events-american-samoa
       /world/tax-benefits-pensions-and-working-abroad-american-samoa
       /world/trade-and-invest-american-samoa
       /world/emergency-help-for-british-nationals-american-samoa
       /world/birth-death-and-marriage-abroad-american-samoa
       /world/living-in-american-samoa
       /world/coming-to-the-uk-american-samoa
       /world/travelling-to-american-samoa
       /world/passports-and-emergency-travel-documents-american-samoa
       /world/american-samoa
       /world/british-embassy-or-high-commission-lesotho
       /work/pensions-and-ageing-society
       /money/personal-tax-income-tax-welsh-rate-of-income-tax
       /world/myanmar
       /world/news-and-events-myanmar
       /world/emergency-help-for-british-nationals-myanmar
       /world/coming-to-the-uk-myanmar
       /world/travelling-to-myanmar
       /world/passports-and-emergency-travel-documents-myanmar
       /world/british-embassy-or-high-commission-myanmar
       /world/birth-death-and-marriage-abroad-myanmar
       /world/tax-benefits-pensions-and-working-abroad-myanmar
       /world/trade-and-invest-myanmar
       /health-and-social-care/human-fertilisation-and-embryology
       /health-and-social-care/exercise-physical-activity
       /education/inspection-of-non-maintained-schools
       /education/pupil-performance-in-schools
       /education/home-schooling
       /education/dealing-with-problems-at-school
       /education/help-with-school-costs
       /education/sending-a-child-to-school
       /education/learning-records-service-lrs
       /education/running-a-further-or-higher-education-institution
       /education/financial-management-for-further-education-providers
       /education/further-education-financial-management-and-data-collection
       /education/further-and-higher-education-courses-and-qualifications
       /education/careers-guidance-in-further-and-higher-education
       /education/adult-and-community-learning
       /education/types-of-apprenticeships
       /education/hiring-and-training-and-intern-or-trainee
       /education/becoming-an-apprentice
       /education/hiring-and-training-an-apprentice
       /education/apprenticeships-traineeships-and-internships
       /education/adult-education-funding
       /education/apprenticeships-funding
       /education/further-education-building-and-premises
       /education/european-social-fund-esf-and-skills-funding
       /education/free-meals-for-16-to-18-year-olds
       /education/further-education-funding-data
       /education/dance-and-drama-funding-for-16-to-19-year-olds
       /education/initial-teacher-training-funding
       /education/funding-for-special-educational-needs-and-disability-send
       /education/funding-for-high-needs
       /education/exam-regulation-and-administration
       /education/student-loans-bursaries-and-sponsorship
       /education/school-workforce-censuses
       /education/school-preference-admission-appeals-data-collection
       /education/school-censuses-and-slasc
       /education/phonics-screening-checks
       /education/key-stage-1-and-2-assessments-data-collection
       /world/british-embassy-or-high-commission-st-helena-ascension-and-tristan-da-cunha
       /health-and-social-care/end-of-life-care
       /health-and-social-care/pharmacy
       /crime-justice-and-law/counter-extremism
       /transport/transporting-abnormal-loads
       /health-and-social-care/diabetes
       /business-and-industry/overseas-businesses-export-to-uk
       /government/visit-europe-after-brexit
       /world/syria
       /world/british-embassy-or-high-commission-syria
       /business-and-industry/state-aid
       /health-and-social-care/health-protection
       /health-and-social-care/population-screening-programmes
       /health-and-social-care/heart-disease
       /world/north-macedonia
       /health-and-social-care/learning-disabilities
       /health-and-social-care/cancer-research-and-treatment
       /world/emergency-help-for-british-nationals-macedonia
       /world/tax-benefits-pensions-and-working-abroad-macedonia
       /world/living-in-macedonia
       /world/coming-to-the-uk-macedonia
       /world/travelling-to-macedonia
       /world/passports-and-emergency-travel-documents-macedonia
       /world/british-embassy-or-high-commission-macedonia
       /world/trade-and-invest-macedonia
       /world/news-and-events-macedonia
       /world/birth-death-and-marriage-abroad-macedonia
       /going-and-being-abroad/help-british-nationals-overseas-europe-macedonia
       /health-and-social-care/medicines-medical-devices-blood
       /health-and-social-care/medicines-medical-devices-blood-blood-regulation-safety
       /health-and-social-care/research-and-innovation-in-health-and-social-care
       /health-and-social-care/obesity
       /health-and-social-care/technology-in-health-and-social-care
       /health-and-social-care/carers-health
       /health-and-social-care/careers-health-social-care
       /health-and-social-care/health-social-care-training
       /health-and-social-care/health-workforce
       /childcare-parenting/childrens-health
       /business-and-industry/directorship-disqualification
       /transport/hs2-archaeology
       /government/brexit-guidance-for-uk-citizens
       /health-and-social-care/health-protection-migrant-health-guide
       /world/british-embassy-or-high-commission-mauritania
       /entering-staying-uk/inspections-of-border-immigration-asylum-services
       /housing-local-and-community/homelessness-rough-sleeping
       /health-and-social-care/oral-health
       /transport/ship-crew-health-and-safety
       /business-and-industry/product-safety
       /transport/hgv-and-goods-carriage-vehicle-licensing
       /transport/taxi-and-private-hire-vehicle-licensing
       /transport/public-service-vehicles-licensing
       /health-and-social-care/antimicrobial-resistance
       /business-and-industry/high-streets-and-town-centres
       /health-and-social-care/abortion
       /transport/car-motorcycle-and-van-mot-tests
       /transport/driver-cpc-training
       /housing-local-and-community/neighours-noise-pests
       /transport/driver-cpc-training-centres
       /business/economic-development-in-coastal-and-seaside-areas
       /housing-local-and-community/party-walls
       /health-and-social-care/mental-health-service-reform
       /health-and-social-care/mental-health
       /health-and-social-care/long-term-health-conditions
       /health-and-social-care/dementia
       /health-and-social-care/autism
       /health-and-social-care/health-conditions
       /health-and-social-care/dentistry
       /health-and-social-care/ophthalmology
       /health-and-social-care/healthy-eating
       /society-and-culture/community-integration
       /regional-and-local-government/council-tax-reform
       /childcare-parenting/intercountry-adoption
       /defence-and-armed-forces/armed-forces-support-for-activities-in-the-uk
       /defence-and-armed-forces/weapons-proliferation
       /defence-and-armed-forces/uk-nuclear-deterrent
       /environment/animal-welfare
       /environment/pets
       /environment/wildlife-habitat-conservation
       /environment/protected-sites-species
       /society-and-culture/young-people
       /health-and-social-care/drug-misuse-and-dependency
       /health-and-social-care/harmful-drinking
       /health-and-social-care/smoking
       /health-and-social-care/health-improvement
       /health-and-social-care/public-health
       /money
       /crime-justice-and-law
       /defence-and-armed-forces
       /work
       /life-circumstances
       /welfare
       /housing-local-and-community
       /society-and-culture
       /health-and-social-care
       /international
       /regional-and-local-government
       /government/all
       /government/content-publishing
       /environment/bovine-tuberculosis
       /environment/cattle-identification-registration-movements
       /environment/preventing-and-reporting-disease
       /environment
       /environment/rural-economy-and-community
       /environment/animal-and-plant-health
       /environment/economic-growth-in-rural-areas
       /environment/parks-trails-nature-reserves
       /environment/access-to-the-countryside
       /environment/environmental-management-water-hydropower
       /housing-local-and-community/energy-efficiency-in-buildings
       /housing-local-and-community/household-energy
       /environment/food-and-farming
       /environment/marine
       /environment/waste-and-recycling
       /environment/radioactive-and-nuclear-substances-and-waste
       /environment/waste-environment
       /environment/waste-management
       /environment/water-and-sewerage-services
       /government/europe
       /government/cyber-security
       /government/sustainable-development
       /health-and-social-care/health-protection-radiation
       /environment/environmental-management-environmental-risk-management-contaminated-land
       /environment/commercial-fishing-fisheries-and-vessels
       /environment/rural-development-land-management
       /environment/coal
       /environment/wildlife-and-animal-welfare
       /environment/biodiversity-and-ecosystems
       /environment/wildlife-animals-biodiversity-and-ecosystems
       /environment/river-maintenance-flooding-coastal-erosion
       /environment/pollution-and-environmental-quality
       /environment/pollution-and-spills
       /transport/road-transport-emissions
       /environment/hydrography
       /environment/marine-environment
       /environment/marine-planning
       /environment/marine-licences
       /environment/treasure-wrecks
       /environment/marine-fisheries
       /environment/freshwater-fisheries
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-vessel-licensing-and-lists
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-vessel-monitoring-systems
       /environment/fisheries-funding
       /environment/vessel-surveys-inspections
       /environment/vessel-licensing
       /environment/vessel-crew-safety-certification
       /environment/fishing-vessels
       /environment/species-protection-and-marine-conservation
       /environment/fishing-quota-and-catch-limits
       /environment/fishing-regulations-monitoring-enforcement
       /business-and-industry/embargoes-and-sanctions
       /business-and-industry/customs-declarations-duties-tariffs
       /society-and-culture/equality
       /transport/road-traffic
       /money/personal-tax-living-working-abroad-offshore-living-and-working-abroad
       /money/tax-evasion-and-avoidance
       /money/personal-tax-reform
       /money/personal-tax-capital-gains-tax-business
       /money/personal-tax-capital-gains-tax-shares-and-investments
       /money/personal-tax-capital-gains-tax-property
       /money/personal-tax-capital-gains-tax-personal-possessions
       /money/personal-tax-income-tax-scottish-rate-of-income-tax
       /money/income-tax
       /money/personal-tax-income-tax-pensions
       /money/personal-tax-income-tax-company-benefits-and-share-schemes
       /money/personal-tax-income-tax-student-jobs-and-loans
       /money/personal-tax-income-tax-special-types-of-pay
       /money/personal-tax-income-tax-overpayments-and-underpayments
       /money/personal-tax-income-tax-rates-allowances-and-reliefs
       /money/self-assessment
       /money/personal-tax-self-assessment-paying-your-tax-bill
       /money/personal-tax-self-assessment-refunds-appeals-and-penalties
       /money/personal-tax-self-assessment-records-you-must-keep
       /money/personal-tax-self-assessment-filing-a-tax-return
       /money/personal-tax-self-assessment-registering-for-self-assessment
       /money/leaving-uk
       /money/non-resident-landlord-scheme
       /money/trusts
       /money/savings-investment-tax
       /money/personal-tax-savings-investment-tax-guidance-for-financial-institutions
       /money/personal-tax-savings-investment-tax-tax-on-shares
       /money/personal-tax-savings-investment-tax-tax-on-savings
       /money/personal-tax-savings-investment-tax-tax-efficient-savings-and-investments
       /money/living-working-abroad-offshore
       /money/personal-tax-living-working-abroad-offshore-rules-for-specific-occupations
       /money/dealing-with-hmrc-tax-compliance-clearances-and-approvals
       /money/dealing-with-hmrc-tax-compliance-non-payment-and-fraud
       /money/dealing-with-hmrc-tax-compliance-disputes
       /money/dealing-with-hmrc-tax-compliance-compliance-checks
       /money/tax-agent-guidance
       /money/dealing-with-hmrc-tax-agent-guidance-money-laundering-regulations
       /money/dealing-with-hmrc-tax-agent-guidance-working-with-hmrc-joint-initiatives
       /money/dealing-with-hmrc-tax-agent-guidance-compliance-checks
       /money/dealing-with-hmrc-tax-agent-guidance-appeals-and-penalties
       /money/dealing-with-hmrc-tax-agent-guidance-agent-authorisation
       /money/dealing-with-hmrc-software-development-working-in-partnership
       /money/dealing-with-hmrc-software-development-hmrc-recognition-scheme
       /money/dealing-with-hmrc-software-development
       /money/dealing-with-hmrc-software-development-new-to-hmrc-development
       /money/dealing-with-hmrc-software-development-software-development-support
       /money/personal-tax-inheritance-tax-reliefs
       /money/personal-tax-inheritance-tax
       /money/personal-tax-inheritance-tax-paying-hmrc
       /money/personal-tax
       /money/personal-tax-inheritance-tax-working-out-the-tax
       /money/national-insurance
       /money/personal-tax-national-insurance-rates-and-classes
       /money/personal-tax-national-insurance-voluntary-contributions
       /money/personal-tax-inheritance-tax-wills-and-probate
       /money/personal-tax-national-insurance-refunds
       /money/personal-tax-national-insurance-national-insurance-numbers
       /money/coming-to-uk
       /money/capital-gains-tax
       /money/foreign-entertainer-rules
       /money/personal-tax-capital-gains-tax-divorce-and-separation
       /money/personal-tax-capital-gains-tax-paying-hmrc
       /money/business-tax-insurance-premium-tax-paying-insurance-premium-tax
       /money/dealing-with-hmrc
       /money/dealing-with-hmrc-paying-hmrc-payment-problems
       /money/paying-hmrc
       /money/dealing-with-hmrc-paying-hmrc-paye
       /money/dealing-with-hmrc-paying-hmrc-tax-credit-overpayments
       /money/dealing-with-hmrc-paying-hmrc-transport-and-environmental-duties
       /money/dealing-with-hmrc-paying-hmrc-vat
       /money/dealing-with-hmrc-paying-hmrc-property-taxes
       /money/dealing-with-hmrc-paying-hmrc-pension-schemes
       /money/dealing-with-hmrc-paying-hmrc-shares
       /money/dealing-with-hmrc-paying-hmrc-money-laundering-regulation-fees
       /money/dealing-with-hmrc-paying-hmrc-inheritance-tax
       /money/dealing-with-hmrc-paying-hmrc-insurance-premium-tax
       /money/dealing-with-hmrc-paying-hmrc-income-tax-and-national-insurance
       /money/dealing-with-hmrc-paying-hmrc-gambling-duties
       /money/dealing-with-hmrc-paying-hmrc-corporation-tax
       /money/dealing-with-hmrc-paying-hmrc-construction-industry-scheme-through-paye
       /money/dealing-with-hmrc-paying-hmrc-child-benefit-overpayments
       /money/dealing-with-hmrc-paying-hmrc-alcohol-duties
       /money/dealing-with-hmrc-paying-hmrc-capital-gains-tax
       /money/phishing-scams
       /money/shared-workspace
       /money/complaints-appeals
       /money/dealing-with-hmrc-tax-avoidance-identifying-avoidance-schemes
       /money/tax-avoidance
       /money/dealing-with-hmrc-tax-avoidance-disclosing-avoidance-schemes
       /money/dealing-with-hmrc-tax-avoidance-disguised-remuneration-schemes
       /money/dealing-with-hmrc-tax-compliance-international-agreements-and-fatca
       /money/tax-compliance
       /money/dealing-with-hmrc-tax-compliance-reporting-tax-evasion
       /money/dealing-with-hmrc-tax-compliance-disclosing-offshore-income
       /money/oil-and-gas
       /money/business-tax-international-tax-shipping
       /money/corporation-tax
       /money/business-tax-international-tax-double-taxation
       /money/business-tax-corporation-tax-filing-your-return
       /money/business-tax-corporation-tax-changes-to-your-company
       /money/business-tax-corporation-tax-payments-and-refunds
       /money/business-tax-corporation-tax-reliefs
       /money/business-tax-corporation-tax-working-out-your-corporation-tax
       /money/pension-scheme-administration
       /money/business-tax-corporation-tax-preparing-accounts-for-corporation-tax
       /money/business-tax-pension-scheme-administration-overseas-schemes
       /money/business-tax-pension-scheme-administration-tax-on-pensions
       /money/business-tax-pension-scheme-administration-paying-into-a-pension-scheme
       /money/business-tax-pension-scheme-administration-administering-a-pension-scheme
       /money/business-tax-pension-scheme-administration-pension-scheme-trustees
       /money/business-tax-vat-rules-for-particular-trades
       /money/vat
       /money/business-tax-vat-exporting-goods-and-services
       /money/business-tax-vat-overseas-businesses-and-uk-vat
       /money/business-tax-vat-importing-goods-and-services
       /money/business-tax-vat-vat-moss
       /money/business-tax-vat-charging-vat
       /money/business-tax-vat-vat-returns
       /money/business-tax-vat-reclaiming-vat-on-a-new-home
       /money/business-tax-vat-paying
       /money/business-tax-vat-exchange-rates
       /money/business-tax-reform
       /money/business-tax-vat-accounting-for-vat
       /money/climate-change-levy
       /money/business-tax-insurance-premium-tax
       /money/business-tax-employment-related-securities-national-insurance-transfers
       /money/business-tax-employment-related-securities-asset-valuation
       /money/business-tax-employment-related-securities-returns-and-notifications
       /money/landfill-tax
       /money/business-tax-landfill-tax-payments-and-reliefs
       /money/gambling-duties
       /money/business-tax-gambling-duties-machine-games-duty
       /money/business-tax-gambling-duties-general-betting-duty-pool-betting-duty-and-remote-gaming-duty
       /money/business-tax-gambling-duties-paying-hmrc
       /money/business-tax-gambling-duties-lottery-duty
       /money/business-tax-gambling-duties-gaming-duty
       /money/business-tax-gambling-duties-bingo-duty
       /money/tobacco-products-duty
       /money/business-tax-tobacco-products-duty-payments-and-reliefs
       /money/investment-schemes
       /money/business-tax-tobacco-products-duty-moving-and-storing-goods
       /money/business-tax-investment-schemes-collective-investment-schemes
       /money/business-tax-investment-schemes-venture-capital-schemes
       /money/stamp-taxes
       /money/business-tax-stamp-taxes-file-your-sdlt-return
       /money/business-tax-stamp-taxes-annual-tax-on-enveloped-dwellings
       /money/business-tax-stamp-taxes-sdlt-on-specific-transactions
       /money/business-tax-stamp-taxes-stamp-duty-before-december-2003
       /money/business-tax-stamp-taxes-pay-your-sdlt-bill
       /money/alcohol-duties
       /money/fuel-duty
       /money/business-tax-alcohol-duties-moving-and-storing-goods
       /money/business-tax-alcohol-duties-payments-and-reliefs
       /money/business-tax-fuel-duty-moving-and-storing-goods
       /money/business-tax-fuel-duty-payments-and-reliefs
       /money/international-tax
       /money/business-tax-paye-changes-to-the-business-that-affect-paye
       /money/business-tax-paye-expenses-and-benefits
       /money/business-tax-paye-statutory-pay-and-leave
       /money/business-tax-paye-employees-joining-leaving-or-changing-their-circumstances
       /money/business-tax-paye-annual-paye-and-payroll-tasks
       /money/life-insurance-policies
       /money/business-tax-paye-paying-hmrc
       /money/business-tax-ir35-employment-intermediaries
       /money/business-tax-paye-registering-and-getting-started
       /money/ir35
       /money/business-tax-ir35-off-payroll-working-rules
       /money/business-tax-ir35-employment-status
       /money/stamp-duty-on-shares
       /money/capital-allowances
       /money/business-tax-stamp-duty-on-shares-stamp-tax-on-electronic-shares
       /money/business-tax-stamp-duty-on-shares-stamp-tax-on-paper-shares
       /money/air-passenger-duty
       /money/business-tax-aggregates-levy-payments-and-reliefs
       /money/business-tax-construction-industry-scheme-payments
       /money/aggregates-levy
       /money/business-tax-construction-industry-scheme-contractors
       /money/construction-industry-scheme
       /money/business-tax-construction-industry-scheme-subcontractors
       /money/employment-related-securities
       /money/business-tax-employment-related-securities-saye-bonus-rates
       /money/business-tax-money-laundering-regulations-problems-and-compliance-checks
       /money/business-tax-money-laundering-regulations-registration-for-specific-business-types
       /money/expenses-employee-benefits
       /money/court-claims-debt-bankruptcy
       /money/money-laundering-regulations
       /money/business-tax-money-laundering-regulations-your-role-under-the-regulations
       /money/business-tax-large-midsize-business-guidance-large-businesses
       /money/business-tax
       /money/large-midsize-business
       /money/paye
       /money/business-tax-large-midsize-business-guidance-mid-sized-businesses
       /money/business-tax-paye-special-types-of-employee-pay
       /defence/international-defence-commitments
       /defence/defence-armed-forces-ministry-of-defence-estate-military-crash-sites
       /defence/defence-armed-forces-ministry-of-defence-estate-sale-of-land
       /defence/ministry-of-defence-estate
       /defence/defence-armed-forces-ministry-of-defence-estate-film-locations
       /defence/defence-armed-forces-ministry-of-defence-estate-public-access
       /defence/military-equipment-logistics-technology
       /defence/stability-in-the-western-balkans
       /defence/military-recruitment-training-operations
       /defence/armed-forces-and-ministry-of-defence-reform
       /defence/defence-armed-forces-ministry-of-defence-estate-art-collection
       /defence-and-armed-forces/armed-forces-covenant
       /defence/nuclear-disarmament
       /defence/support-services-veterans-families
       /defence/support-services-military-defence-personnel-families
       /defence/defence-armed-forces-support-services-military-defence-personnel-families-pensions-and-compensation
       /defence/defence-armed-forces-support-services-military-defence-personnel-families-housing-and-accommodation
       /defence/working-armed-forces
       /defence/defence-armed-forces-support-services-military-defence-personnel-families-british-forces-post-office
       /defence/defence-armed-forces-military-awards-commemorations-honours-and-awards
       /defence/defence-armed-forces-military-awards-commemorations-medals
       /defence/military-awards-commemorations
       /defence/defence-armed-forces-military-awards-commemorations-veterans
       /crime-justice-and-law/byelaws
       /crime-justice-and-law/data-protection
       /crime-justice-and-law/legal-aid-for-providers-high-cost-complex-cases
       /crime-justice-and-law/counter-terrorism
       /crime-justice-and-law/reporting-crimes-compensation
       /crime-justice-and-law/policing
       /crime-justice-and-law/courts-sentencing-tribunals
       /crime-justice-and-law/legal-aid-for-providers-crime
       /crime-justice-and-law/knife-gun-and-gang-crime
       /crime-justice-and-law/legal-aid-reform
       /crime-justice-and-law/reoffending-and-rehabilitation
       /crime-justice-and-law/attorney-general-guidance-to-legal-profession
       /crime-justice-and-law/forced-marriage
       /crime-justice-and-law/domestic-violence
       /crime-justice-and-law/intellectual-property-law-practice-copyright
       /crime-justice-and-law/law-practice
       /crime-justice-and-law/intellectual-property-law-practice-designs
       /crime-justice-and-law/intellectual-property-law-practice-patents
       /crime-justice-and-law/intellectual-property-law-practice-trade-marks
       /crime-justice-and-law/family-justice-system
       /crime-justice-and-law/justice-system-transparency
       /crime-justice-and-law/violence-against-women-and-girls
       /crime-justice-and-law/criminal-justice-reform
       /crime-justice-and-law/civil-justice-reform
       /crime-justice-and-law/criminal-record-disclosure
       /crime-justice-and-law/victims-of-crime
       /crime-justice-and-law/sentencing-reform
       /crime-justice-and-law/administrative-justice-reform
       /crime-justice-and-law/legal-aid-for-providers-contracts
       /crime-justice-and-law/young-people-and-the-law
       /crime-justice-and-law/prisons-probation
       /crime-justice-and-law/rights
       /crime-justice-and-law/statutory-rights
       /crime-justice-and-law/crime-prevention
       /crime-justice-and-law/legal-aid-for-providers
       /crime-justice-and-law/prisons-probation-healthcare
       /crime-justice-and-law/prisons-probation-mappa
       /crime-justice-and-law/legal-aid-for-providers-electronic-working
       /crime-justice-and-law/legal-aid-for-providers-tenders
       /crime-justice-and-law/legal-aid-for-providers-payments-processing
       /international/foreign-affairs
       /international/government-topics-foreign-affairs-conflict-in-fragile-states
       /international/afghanistan
       /international/government-topics-foreign-affairs-iran-s-nuclear-programme
       /international/government-topics-foreign-affairs-uk-overseas-territories
       /international/government-topics-foreign-affairs-piracy-off-the-coast-of-somalia
       /international/international-aid-and-development
       /international/peace-stability-in-me-and-north-africa
       /international/government-topics-foreign-affairs-falkland-islanders-right-to-self-determination
       /international/women-and-girls-in-developing-countries
       /international/health-in-developing-countries
       /international/overseas-aid-transparency
       /international/governance-in-developing-countries
       /international/economic-growth-in-developing-countries
       /international/overseas-aid-effectiveness
       /international/climate-change-impact-in-developing-countries
       /international/hunger-and-malnutrition-in-developing-countries
       /international/education-in-developing-countries
       /international/humanitarian-emergencies
       /international/water-and-sanitation-in-developing-countries
       /international/human-rights-internationally
       /international/uk-prosperity-and-security-asia-latin-america-and-africa
       /international/the-commonwealth
       /international/anti-corruption
       /international/sexual-violence-in-conflict
       /environment/forests-and-woodland
       /environment/wildlife-biodiversity
       /environment/recycling-waste-management
       /environment/flooding-extreme-weather
       /environment/fishing-hunting
       /environment/countryside
       /environment/coasts
       /environment/boats-waterways
       /environment/planning-development-protected-sites-species-land-sites
       /environment/planning-development-protected-sites-species-land-species
       /environment/planning-development-protected-sites-species-marine-sites-and-species
       /environment/planning-development-protected-sites-species-science-and-evidence
       /environment/environmental-management-wildlife-habitat-conservation-plants
       /environment/environmental-management-wildlife-habitat-conservation-other-wildlife-licensing
       /environment/environmental-management-wildlife-habitat-conservation-reptiles-and-amphibians
       /environment/environmental-management-wildlife-habitat-conservation-mammals
       /environment/environmental-management-wildlife-habitat-conservation-birds
       /environment/environmental-management-wildlife-habitat-conservation-fish-and-shellfish
       /environment/environmental-management-wildlife-habitat-conservation-invertebrates
       /environment/producing-distributing-food-dairy-milk-production
       /environment/producing-distributing-food-food-labelling
       /environment/producing-distributing-food-egg-production-marketing
       /environment/producing-distributing-food-crops-horticulture
       /environment/producing-distributing-food-plant-health-seeds
       /environment/keeping-farmed-animals-veterinary-medicines
       /environment/keeping-farmed-animals
       /environment/keeping-farmed-animals-shows-fairs-markets
       /environment/keeping-farmed-animals-sheep-identity-registration
       /environment/keeping-farmed-animals-preventing-disease
       /environment/keeping-farmed-animals-poultry-registration
       /environment/keeping-farmed-animals-pig-identity-registration-movements
       /environment/keeping-farmed-animals-import-export
       /environment/keeping-farmed-animals-dealing-with-dead-animals
       /environment/keeping-farmed-animals-deer-farming
       /environment/keeping-farmed-animals-cattle-movement
       /environment/keeping-farmed-animals-cattle-deaths
       /environment/keeping-farmed-animals-bovine-tb
       /environment/farming-industry-regulation
       /environment/keeping-farmed-animals-animal-feed
       /environment/common-agricultural-policy-reform
       /environment/food-and-farming-industry
       /environment/rural-and-countryside
       /environment/outdoor-access-recreation-parks-trails-nature-reserves-nature-reserves
       /environment/outdoor-access-recreation-parks-trails-nature-reserves-trails
       /environment/outdoor-access-recreation-parks-trails-nature-reserves-parks
       /environment/energy-and-climate-change-evidence-and-analysis
       /environment/climate-change-energy-low-carbon-energy
       /environment/climate-change-energy-energy-security
       /environment/climate-change-energy-international-climate-change
       /environment/climate-change-energy-energy-efficiency
       /environment/climate-change-energy-energy-prices-bills
       /environment/climate-change-energy-climate-change-agreements
       /environment/climate-change-energy-emissions
       /environment/farming-food-grants-payments
       /environment/farming-food-grants-payments-school-milk-scheme
       /environment/farming-food-grants-payments-rural-grants-payments
       /environment/farming-food-grants-payments-rural-grants-payments-other
       /environment/countryside-stewardship
       /environment/farming-food-grants-payments-rural-grants-payments-cross-compliance
       /environment/farming-food-grants-payments-rural-grants-payments-common-agricultural-policy-cap-reform
       /environment/farming-food-grants-payments-rural-grants-payments-rural-development
       /environment/farming-food-grants-payments-rural-grants-payments-online-applications-and-payments
       /environment/farming-food-grants-payments-private-storage-aid
       /environment/farming-food-grants-payments-rural-grants-payments-basic-payment-scheme-bps
       /environment/producing-distributing-food
       /environment/farming-food-grants-payments-intervention-schemes
       /environment/producing-distributing-food-meat-production
       /environment/producing-distributing-food-sugar
       /environment/producing-distributing-food-import-export
       /environment/commercial-fishing-fisheries-funding-fisheries-challenge-fund
       /environment/commercial-fishing-fisheries-funding-european-maritime-and-fisheries-fund-emff
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-fisheries-statistics
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-first-sale-marine-fish
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-sales-notes-and-electronic-recording-systems
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-enforcement-news
       /environment/commercial-fishing-fisheries-regulations-monitoring-enforcement-catch-quota-trials
       /environment/coal-reports-data
       /environment/coal-property-development
       /environment/coal-water-management
       /environment/coal-permits-licences
       /environment/climate-change-energy
       /environment/transport-environment
       /environment/climate-change-adaptation
       /environment/climate-change-international-action
       /environment/greenhouse-gas-emissions
       /environment/water-industry
       /business/environmental-management-water-drought-and-water-availability
       /business/environmental-management-water-water-pollution
       /business/environmental-management-water-water-quality
       /business/environmental-management-water-impound-store-water
       /business/environmental-management-water-discharge-water
       /business/environmental-management-water-abstract-take-water
       /environment/chemicals
       /environment/environmental-management-chemicals-mercury
       /environment/environmental-management-chemicals-f-gases-and-hcfcs
       /environment/environmental-management-chemicals-contaminated-land
       /environment/environmental-management-chemicals-reach-regulations
       /environment/environmental-management-chemicals-polychlorinated-biphenyl-pcbs
       /environment/oil-spills
       /environment/oil-and-gas-licensing
       /environment/oil-and-gas-onshore-oil-and-gas
       /environment/oil-and-gas-finance-and-taxation
       /environment/oil-and-gas-finance-and-taxation-tax-and-profits
       /environment/oil-and-gas-finance-and-taxation-market-values
       /environment/oil-and-gas-infrastructure-and-decommissioning
       /environment/oil-and-gas-fields-and-wells
       /environment/oil-and-gas-exploration-and-production
       /environment/oil-and-gas-carbon-capture-and-storage
       /environment/harbour-orders
       /environment/marine-pollution-prevention
       /environment/environmental-management-marine-marine-protection-and-wildlife
       /environment/environmental-management-marine-sea-fishing
       /environment/environmental-management-marine-harbours
       /environment/environmental-management-marine-marine-plans
       /environment/environmental-management-marine-pollution-and-spills
       /environment/environmental-management-land-management-pollution
       /environment/environmental-management-land-management-protected-sites
       /environment/environmental-management-land-management-weeds-and-invasive-non-native-plants
       /environment/environmental-management-land-management-farming
       /environment/environmental-management-land-management-hedgerows
       /environment/environmental-management-land-management-contaminated-land
       /environment/environmental-management-land-management-commons-and-greens
       /environment/assessing-environmental-impact
       /environment/environmental-risk-management
       /environment/environmental-management-environmental-risk-management-flood-risk
       /environment/environmental-management-environmental-risk-management-radiation
       /environment/environmental-management-environmental-risk-management-reduce-and-report-pollution
       /environment/high-speed-2-environment
       /environment/using-waste
       /environment/disposing-of-waste
       /environment/waste-water-charges
       /environment/moving-waste
       /environment/waste-permits-and-licences
       /environment/environmental-management-waste-clinical-waste
       /environment/environmental-management-waste-electrical-waste
       /environment/environmental-management-waste-batteries
       /environment/environmental-management-waste-hazardous-waste
       /environment/environmental-management-waste-report-a-waste-problem
       /environment/parking-public-transport-environment
       /environment/driving-parking-public-transport-environment-environment-and-emissions
       /environment/driving-parking-public-transport-environment-parking
       /environment/driving-parking-public-transport-environment-public-transport-and-bus-passes
       /environment/driving-parking-public-transport-environment-blue-badges
       /environment/boating-and-inland-waterways
       /environment/environmental-permits
       /environment/environmental-management-flooding-coastal-change-after-a-flood
       /environment/environmental-management-flooding-coastal-change-during-a-flood
       /environment/environmental-management-flooding-coastal-change-before-a-flood
       /environment/environmental-management-flooding-coastal-change-report-flooding
       /environment/environmental-management-flooding-coastal-change-flood-maps-and-flood-risk
       /environment/environmental-management-flooding-coastal-change-flood-warnings
       /environment/packaging-waste
       /environment/treating-waste
       /environment/end-of-waste
       /environment/storing-waste
       /environment/environmental-management-flooding-coastal-change-investment-and-funding
       /environment/topic
       /environment/environmental-management-flooding-coastal-change-working-on-or-near-a-river-flood-or-sea-defence
       /environment/environmental-management-flooding-coastal-change-risk-management-plans
       /environment/environmental-management-flooding-coastal-change-reservoirs
       /environment/environmental-management-flooding-coastal-change-coastal-erosion
       /environment/environmental-management-flooding-coastal-change-river-maintenance
       /environment/environmental-management-flooding-coastal-change-flood-defence-schemes
       /health-and-social-care/health-emergency-planning
       /health-and-social-care/health-protection-chemical-and-environmental-hazards
       /health-and-social-care/screening-quality-assurance
       /business-and-industry/consumer-rights-and-issues
       /business-and-industry/regulation-reform
       /business-and-industry/media-and-communications
       /business-and-industry/financial-services
       /business-and-industry/business-and-the-environment
       /business-and-industry/dismissals-redundancies
       /employment/redundancies-dismissals
       /employment/contract-working-hours
       /work/health-safety-at-work
       /business-and-industry/manufacturing
       /business-and-industry/uk-economy
       /business-and-industry/industrial-strategy
       /business-and-industry/free-trade
       /business-and-industry/outward-investment
       /business-and-industry/inward-investment
       /business-and-industry/importing
       /business-and-industry/trade-barriers
       /business-and-industry/exporting
       /business-and-industry/digital-trade
       /business/business-tax-import-export-exchange-rates
       /business/business-imports-wood-packaging
       /business/business-imports-commodity-codes-and-reporting
       /business-and-industry/export-finance
       /business-and-industry/export-controls
       /business-and-industry/trade-restrictions-on-exports
       /business-and-industry/regional-growth-fund
       /business-and-industry/city-deals-and-growth-deals
       /business/uk-economic-growth
       /business/local-enterprise-partnerships-leps-and-enterprise-zones
       /business/management-of-the-european-regional-development-fund
       /business-and-industry/charities-and-social-enterprises
       /business-and-industry/science-and-innovation
       /business-and-industry/trade-and-investment
       /business-and-industry/running-charity-trustee-role-board
       /business-and-industry/running-charity-fundraising
       /business-and-industry/running-charity-money-accounts
       /business-and-industry/community-interest-companies
       /business-and-industry/scientific-research-and-development
       /business-and-industry/research-and-development
       /business-and-industry/animal-research-and-testing
       /business/business-exports-commodity-codes-and-reporting
       /business/business-tax-import-export-uk-trade-tariff-and-classification-of-goods
       /business-and-industry/media-and-creative-industries
       /business/broadband-investment
       /business/communications-and-telecomms
       /business/financial-services-regulation
       /business/access-to-financial-services
       /business/bank-regulation
       /business/intellectual-property
       /business/competition
       /business/consumer-credit-market
       /business/consumer-protection
       /business/company-law-reform
       /business/copyright
       /business/patents
       /business/designs
       /business/trade-marks
       /business/competition-law
       /business/competition-regulatory-appeals-references
       /business/competition-mergers
       /business/competition-markets
       /business/competition-consumer-protection
       /business/competition-competition-act-cartels
       /business-and-industry/energy-demand-reduction-in-industry-business-and-the-public-sector
       /business/uk-energy-security
       /business-and-industry/staff-pensions
       /business-and-industry/trade-unions
       /business-and-industry/statutory-leave-time-off
       /business-and-industry/contracts-of-employment-working-hours
       /business-and-industry/corporate-governance
       /business-and-industry/business-regulation
       /business-and-industry/limited-companies-and-partnerships
       /business/finance-support
       /business/premises-rates
       /business-and-industry/payroll
       /business-and-industry/recruiting-hiring
       /business-and-industry/company-registration-filing-running-company-partnerships
       /business-and-industry/company-names
       /business-and-industry/company-registration-filing-running-company-overseas-companies-and-european-companies
       /business-and-industry/company-closure-administration-liquidation-and-insolvency
       /business-and-industry/sale-goods-services-data
       /business-and-industry/energy-industry-and-infrastructure-licensing-and-regulation
       /business-and-industry
       /business-and-industry/running-a-business
       /business-and-industry/business-debt-and-bankruptcy
       /business-and-industry/business-licensing
       /business-and-industry/business-auditing-accounting-reporting
       /business-and-industry/employing-people
       /business-and-industry/business-exports-licences-and-special-rules
       /business/business-tax-import-export-customs-freight-simplified-procedures
       /business/business-tax-import-export-rules-for-specific-goods-and-services
       /business/business-tax-import-export-get-goods-through-customs
       /business-and-industry/import-controls
       /going-and-being-abroad-old
       /business-and-industry/setting-up-running-a-company
       /business-and-industry/importing-exporting
       /business/business-exports-get-export-advice-and-finance
       /government/government-technology-and-digital-services
       /society-and-culture/loneliness
       /housing-local-and-community/planning-and-building
       /going-and-being-abroad/british-nationals-in-the-eu
       /business-and-industry/running-charity
       /welfare/benefits-credits-child-benefit-high-income-tax-charge
       /welfare/support-for-families
       /welfare/child-benefit
       /welfare/tax-credits
       /welfare/entitlement
       /welfare/jobseekers-allowance
       /welfare/universal-credit
       /welfare/welfare-reform
       /welfare/disability
       /welfare/child-maintenance-reform
       /welfare/bereavement
       /welfare/families
       /welfare/heating
       /society-and-culture/tourism
       /society-and-culture/social-mobility
       /society-and-culture/arts-and-culture
       /society-and-culture/sports-and-leisure
       /society-and-culture/national-events-and-ceremonies
       /society-and-culture/equality-rights-and-citizenship
       /society-and-culture/social-investment
       /society-and-culture/social-action
       /society-and-culture/museums-and-galleries
       /society-and-culture/library-services
       /society-and-culture/conservation-of-historic-buildings-and-monuments
       /society-and-culture/2012-olympic-and-paralympic-legacy
       /society-and-culture/recreation
       /society-and-culture/community-amateur-sports-clubs
       /society-and-culture/elite-sports-performance
       /society-and-culture/sports-participation
       /society-and-culture/poverty-and-social-justice
       /society-and-culture/government
       /society-and-culture/charities-honours
       /society-and-culture/citizenship
       /society-and-culture/community-and-society
       /society-and-culture/national-lottery-funding
       /regional-and-local-government/local-government-spending
       /regional-and-local-government/northern-ireland
       /regional-and-local-government/localism
       /regional-and-local-government/scotland
       /regional-and-local-government/local-councils
       /regional-and-local-government/local-government-business-rates-your-rateable-value
       /regional-and-local-government/northern-ireland-security
       /regional-and-local-government/northern-ireland-economy
       /regional-and-local-government/northern-ireland-political-stability
       /regional-and-local-government/northern-ireland-community-relations
       /regional-and-local-government/scottish-constitution
       /regional-and-local-government/scottish-devolution
       /regional-and-local-government/wales
       /regional-and-local-government/local-government-local-housing-allowance
       /regional-and-local-government/local-government-data-collection-reporting
       /regional-and-local-government/local-government-council-tax]
  end
end
