class ValidTags
  ALLOWED_TAGS = %i[
    aircraft_category
    aircraft_type
    alert_type
    algorithmic_transparency_record_function
    appear_in_find_eu_exit_guidance_business_finder
    assessment_date
    business_activity
    business_sizes
    business_stages
    case_state
    case_type
    certificate_status
    closed_date
    closing_date
    commodity_type
    content_purpose_subgroup
    content_purpose_supergroup
    content_store_document_type
    continuation_link
    country
    date_of_occurrence
    destination_country
    development_sector
    dfid_authors
    dfid_document_type
    dfid_review_status
    dfid_theme
    document_type
    eligible_entities
    employ_eu_citizens
    eu_uk_government_funding
    first_published_at
    flood_and_coastal_erosion_category
    format
    fund_state
    fund_type
    funding_amount
    funding_source
    grant_type
    hidden_indexable_content
    industries
    intellectual_property
    issued_date
    laid_date
    land_use
    location
    market_sector
    medical_specialism
    oim_project_type
    opened_date
    outcome_type
    personal_data
    policies
    product_alert_type
    public_sector_procurement
    railway_type
    regions
    registration
    report_type
    sector_business_area
    sift_end_date
    sifting_status
    subject
    therapeutic_area
    tiers_or_standalone_items
    topics
    tribunal_decision_categories
    tribunal_decision_category
    tribunal_decision_country
    tribunal_decision_decision_date
    tribunal_decision_judges
    tribunal_decision_landmark
    tribunal_decision_reference_number
    tribunal_decision_sub_categories
    tribunal_decision_sub_category
    types_of_support
    ukhsa_chemical_name
    ukhsa_product_category
    value_of_funding
    vessel_type
    will_continue_on
    withdrawn_date
  ].freeze
end
